<?php
// $Id: spamspan.module,v 1.8 2010/12/18 18:08:01 lakka Exp $

/**
 * @file
 * This module implements the spamspan technique (http://www.spamspan.com ) for hiding email addresses from spambots.
 *
 * If javascript is disabled on the client-side, addresses appear as
 * example [at] example [dot] com.
 *
 * @author Lawrence Akka
 * @copyright 2006-2010, Lawrence Akka
 * @license http://www.gnu.org/licenses/gpl.txt  GPL v 2.0
 *
 */

/**
 *  Set up a regex constant to split an email address into name and domain
 *  parts. The following pattern is not perfect (who is?), but is intended to
 * intercept things which look like email addresses.  It is not intended to
 * determine if an address is valid.  It will not intercept addresses with
 * quoted local parts.
 *
 * @constant string SPAMSPAN_EMAIL
 */
define('SPAMSPAN_EMAIL', "
      ([-\.\~\'\!\#\$\%\&\+\/\*\=\?\^\_\`\{\|\}\w\+^@]+) # Group 1 - Match the name part - dash, dot or
                           #special characters.
     @                     # @
     ((?:        # Group 2
       [-\w]+\.            # one or more letters or dashes followed by a dot.
       )+                  # The whole thing one or more times
       [A-Z]{2,6}          # with between two and six letters at the end (NB
                           # .museum)
     )");

/**
 * Implements hook_help().
 */
function spamspan_help($path, $arg) {
  switch ($path) {
    case 'admin/help#spamspan':
      return t('<p>The SpamSpan module obfuscates email addresses to help prevent spambots from collecting them. It will produce clickable links if JavaScript is enabled, and will show the email address as <code>example [at] example [dot] com</code> if the browser does not support JavaScript.</p><p>To configure the module, select "configure" next to the <a href="admin/filters">input format</a> you\'d like to use. Enable "Hide Email Addresses using the SpamSpan technique" and submit the form. Then select the "configure" tab to choose relevant options.</p>');
  }
}


/**
 * Implements hook_filter_info().
 */
function spamspan_filter_info() {
  $filters['spamspan']   = array(
    'title' => t('SpamSpan email address encoding filter'),
    'description' => t('Attempt to hide email addresses from spam-bots.'),
    'process callback' => '_spamspan_filter_process',
    'settings callback' => '_spamspan_filter_settings',
    'tips callback' => '_spamspan_filter_tips',
    'default settings' => array(
      'spamspan_at' => ' [at] ',
      'spamspan_use_graphic' => 0,
    ),
  );
  return $filters;
}

/**
 * Spamspan filter process callback
 *
 * Scan text and replace email addresses with span tags
 *
 * We are aiming to replace emails with code like this:
 *   <span class="spamspan">
 *   <span class="u">user</span>
 *   [at]
 *   <span class="d">example [dot] com</span>
 *   <span class="t"tag contents></span></span>
 *
 */
function _spamspan_filter_process($text, $filter) {
  // Top and tail the email regexp it so that it is case insensitive and
  // ignores whitespace.
  $emailpattern = "!" . SPAMSPAN_EMAIL . "!ix";

  // Next set up a regex for mailto: URLs.
  // - see http://www.faqs.org/rfcs/rfc2368.html
  // This captures the whole mailto: URL into the second group,
  // the name into the third group and the domain into
  // the fourth. The tag contents go into the fifth.

  $mailtopattern = "!<a\s+                            # opening <a and spaces
      (?:(?:\w+\s*=\s*)(?:\w+|\"[^\"]*\"|'[^']*'))*?  # any attributes
      \s*                                             # whitespace
      href\s*=\s*(['\"])(mailto:"                     # the href attribute
      . SPAMSPAN_EMAIL .                              # The email address
      "(?:\?[A-Za-z0-9_= %\.\-\~\_\&]*)?)" .            # an optional ? followed
                                                      # by a query string. NB
                                                      # we allow spaces here,
                                                      # even though strictly
                                                      # they should be URL
                                                      # encoded
      "\\1                                            # the relevant quote
                                                      # character
      (?:(?:\s+\w+\s*=\s*)(?:\w+|\"[^\"]*\"|'[^']*'))*? # any more attributes
      >                                               # end of the first tag
      (.*?)                                           # tag contents.  NB this
                                                      # will not work properly
                                                      # if there is a nested
                                                      # <a>, but this is not
                                                      # valid xhtml anyway.
      </a>                                            # closing tag
      !ix";

  // The preg_repalce_callback functions below cannot take any additional
  // arguments, so we have to use a global variable to pass the relevant
  // settings.
  $GLOBALS['spamspan_settings'] = $filter->settings;
  // Now we can convert all mailto URLs
  $text = preg_replace_callback($mailtopattern, '_spamspan_callback_mailto', $text);
  // and finally, all bare email addresses
  return preg_replace_callback($emailpattern, '_spamspan_callback_email', $text);
  unset($GLOBALS['spamspan_settings']);
}

/**
 * Settings callback for spamspan filter
 *
 *
 */
function _spamspan_filter_settings($form, $form_state, $filter, $format, $defaults, $filters) {
  $filter->settings += $defaults;


  // spamspan '@' replacement
  $settings['spamspan_at'] = array(
    '#type' => 'textfield',
    '#title' => t('Replacement for "@"'),
    '#default_value' => $filter->settings['spamspan_at'],
    '#required' => TRUE,
    '#description' => t('Replace "@" with this text when javascript is disabled.'),
  );
  $settings['spamspan_use_graphic'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use a graphical replacement for "@"'),
    '#default_value' => $filter->settings['spamspan_use_graphic'],
    '#description' => t('Replace "@" with a graphical representation when javascript is disabled (and ignore the setting "Replacement for @" above).'),
  );
  return $settings;
}


/**
 * Filter tips callback
 */
function _spamspan_filter_tips($filter, $format, $long = FALSE) {
  return t('Each email address will be obfuscated in a human readable fashion or (if JavaScript is enabled) replaced with a spamproof clickable link.');
}


/**
 * The callback functions for preg_replace_callback
 *
 * Replace an email addresses which has been found with the appropriate
 * <span> tags
 *
 * @param $matches
 *  An array containing parts of an email address or mailto: URL.
 * @return
 *  The span with which to replace the email address
 */
function _spamspan_callback_mailto($matches) {
  // take the mailto: URL in $matches[2] and split the query string
  // into its component parts, putting them in $headers as
  // [0]=>"header=contents" etc.  We cannot use parse_str because
  // the query string might contain dots.
  $headers = preg_split('/[&;]/', parse_url($matches[2], PHP_URL_QUERY));
  // if no matches, $headers[0] will be set to '' so $headers must be reset
  if ($headers[0] == '') {
    $headers = array();
  }
  return _spamspan_output($matches[3], $matches[4], $matches[5], $headers);
}

function _spamspan_callback_email($matches) {
  return _spamspan_output($matches[1], $matches[2], '', '');
}

/**
 * A helper function for the callbacks
 *
 * Replace an email addresses which has been found with the appropriate
 * <span> tags
 *
 * @param $name
 *  The user name
 * @param $domain
 *  The email domain
 * @param $contents
 *  The contents of any <a> tag
 * @param $headers
 *  The email headers extracted from a mailto: URL
 * @return
 *  The span with which to replace the email address
 */
function _spamspan_output($name, $domain, $contents, $headers) {

  $settings = $GLOBALS['spamspan_settings'];
  // Replace .'s in the address with [dot]
  $user_name = str_replace(".", " [dot] ", $name);
  $domain = str_replace(".", " [dot] ", $domain);
  $at = $settings['spamspan_use_graphic'] ? '<img alt="at" width="10" src="' . base_path() . drupal_get_path("module", "spamspan") . "/image.gif" . '" />' : $settings['spamspan_at'];


  $output = '<span class="spamspan"><span class="u">' . $user_name . '</span>' . $at . '<span class="d">' . $domain . '</span>';

  // if there are headers, include them as eg (subject: xxx, cc: zzz)
  if (isset($headers) and $headers) {
    foreach ($headers as $value) {
      //replace the = in the headers arrays by ": " to look nicer
      $temp_headers[] = str_replace("=", ": ", $value);
    }
    $output .= '<span class="h"> (' . check_plain(implode(', ', $temp_headers)) . ') </span>';
  }
  // if there are tag contents, include them, between round brackets, unless
  // the contents are an email address.  In that case, we can ignore them.  This
  // is also a good idea because otherise the tag contents are themselves
  // converted into a spamspan, with undesirable consequences - see bug #305464.
  // NB problems may still be caused by edge cases, eg if the tag contents are
  // "blah blah email@example.com ..."
  if (isset($contents) and $contents and   !(preg_match("!^" . SPAMSPAN_EMAIL . "$!ix", $contents))) {
    $output .= '<span class="t"> (' . $contents . ')</span>';
  }
  $output .= "</span>";
  // remove anything except certain inline elements, just in case.  NB nested
  // <a> elements are illegal.  <img> needs to be here to allow for graphic
  // @
  $output = filter_xss($output, $allowed_tags = array('em', 'strong', 'cite', 'b', 'i', 'code', 'span', 'img'));
  return $output;
}


/**
 * A simple utility function wrapping the main processing callback.
 * This function may be called by other modules and themes.
 *
 * @param $text
 *  Text, maybe containing email addresses.
 * @param $settings
 * An associative array of settings to be applied.
 * @return
 *  The input text with emails replaced by spans
 */
function spamspan($text, $settings = array()) {
  //apply default settings
  $defaults = array(
    'spamspan_at' => ' [at] ',
    'spamspan_use_graphic' => 0,
  );

  $defaults += $settings;
  //create a dummy filter object so we can apply the settings
  $filter = new stdClass();
  $filter->settings = $defaults;
  return _spamspan_filter_process($text, $filter);
}